---
- name: check if node is available for ssh
  wait_for_connection:

- name: Run start-zuul-console role
  include_role:
    name: start-zuul-console

- name: confirm that dns is up
  command: "nslookup -retry=60 {{ nslookup_target }}"
