- name: Install dependencies
  command: "helm dep up {{ helm_chart }}"
  args:
    chdir: "{{ zuul_work_dir }}"

- name: Print templated charts
  command: "helm template -n zuul {{ helm_chart }}"
  args:
    chdir: "{{ zuul_work_dir }}"

- name: Deploy templated charts
  shell: |
    set -o pipefail
    helm template -n {{ helm_release_name }} {{ helm_chart }} | kubectl apply -f-
  args:
    executable: /bin/bash
    chdir: "{{ zuul_work_dir }}"

- name: Wait for all pods to become Ready
  include_role:
    name: wait-for-pods