- name: Install pip
  include_role:
    name: ensure-pip
  vars:
    ensure_pip_from_packages_with_python2: '{{ tox_prefer_python2 }}'

- name: Check if tox is installed
  shell: |
    command -v {{ tox_executable }} || exit 1
  args:
    executable: /bin/bash
  register: tox_preinstalled
  failed_when: false

- name: Export preinstalled tox_exectuable
  set_fact:
    tox_executable: '{{ tox_executable }}'
    cacheable: true
  when: tox_preinstalled.rc == 0

- name: Install tox to local env
  when: tox_preinstalled.rc != 0
  block:
    - name: Install tox to local venv
      pip:
        name: tox
        virtualenv_command: '{{ ensure_pip_virtualenv_command }}'
        virtualenv: '{{ tox_venv_path }}'

    - name: Export installed tox_executable path
      set_fact:
        tox_executable: '{{ tox_venv_path }}/bin/tox'
        cacheable: true

- name: Output tox version
  command: "{{ tox_executable }} --version"
