- name: Assert directory set
  assert:
    that: clean_directory_path is defined
    fail_msg: 'Must specify clean_directory_path'

- block:
  - name: Collect files
    find:
      paths: '{{ clean_directory_path }}'
      hidden: True
      recurse: True
    register: _files

  - name: Collect directories
    find:
      paths: '{{ clean_directory_path }}'
      hidden: True
      recurse: True
      file_type: directory
    register: _dirs

  - name: Clean Directory
    file:
      path: '{{ zj_item }}'
      state: absent
    loop: '{{ _files.files + _dirs.files }}'
    loop_control:
      loop_var: zj_item
