- name: Find directories to strip
  set_fact:
    # - take the url, strip of any trailing "/"
    # - find everything on the // side
    # - split it at /'s, then disregrad the host (ignored by parent
    #   flag) and the final directory (the one we want) i.e. -2
    cut_dirs: '{{ zj_artifact.url.rpartition("//")[-1].rstrip("/").split("/") | length - 2 }}'

- name: Recursive download
  # NOTE(ianw): something weird about wget recursive, you want to make
  # sure the directory to download has a trailing "/" or you can get
  # directory errors; something like
  #  http://savannah.gnu.org/bugs/?29647
  # Otherwise this
  #  - drops the host (-nH)
  #  - doesn't walk upwards (--no-parent)
  #  - doesn't save index.html files (maybe this should be optional for docs?)
  #  - cuts out the all the parent directories but the last one
  #
  #  so "https://foo.com/logs/123/abc/dir/the_artifact" gets saved to
  #  {{ download_artifact_directory }}/the_artifact
  command: |
    wget -nH --no-parent --reject="index.html*" --cut-dirs={{ cut_dirs }} -P {{ download_artifact_directory }} -m {{ zj_artifact.url.rstrip("/") + "/" }}
  args:
    # We really want to use wget here, because the get_url type things
    # don't do recursive.
    warn: false
