# Note (dmsimard)
# We explicitely declare a PATH environment variable because '/sbin' is not in
# PATH when using 'become: yes' on some distributions
- include_tasks:
    file: common.yaml
    apply:
      environment:
        PATH: "{{ ansible_env.PATH }}:/sbin:/usr/sbin"
  when: >-
    inventory_hostname in groups['switch'] or
    inventory_hostname in groups['peers']

- include_tasks:
    file: switch.yaml
    apply:
      environment:
        PATH: "{{ ansible_env.PATH }}:/sbin:/usr/sbin"
  when: inventory_hostname in groups['switch']

- include_tasks:
    file: peer.yaml
    apply:
      environment:
        PATH: "{{ ansible_env.PATH }}:/sbin:/usr/sbin"
  when: inventory_hostname in groups['peers']

- name: Persist iptables rules
  include_role:
    name: persistent-firewall
  when: >-
    inventory_hostname in groups['switch'] or
    inventory_hostname in groups['peers']
