# Note, this file is only part of the project definition; there is a project
# definition in each file in this directory as well which is combined with
# this.

- project:
    check:
      jobs:
        - zuul-tox-docs
        - tox-py27
        - tox-py35:
            nodeset: ubuntu-xenial
        - tox-py38
        - tox-py39:
            nodeset: ubuntu-focal
    gate:
      jobs:
        - zuul-tox-docs
        - tox-py27
        - tox-py35:
            nodeset: ubuntu-xenial
        - tox-py38
        - tox-py39:
            nodeset: ubuntu-focal
    promote:
      jobs:
        - zuul-promote-docs
