# Note, this file is only part of the project definition; there is a project
# definition in each file in this directory as well which is combined with
# this.

- project:
    check:
      jobs:
        - zuul-tox-docs
        - tox-py27
        - tox-py38
        - tox-py39:
            nodeset: ubuntu-focal
        - tox-py310:
            nodeset:
              nodes:
                - name: fedora-35
                  label: fedora-35
    gate:
      jobs:
        - zuul-tox-docs
        - tox-py27
        - tox-py38
        - tox-py39:
            nodeset: ubuntu-focal
        - tox-py310:
            nodeset:
              nodes:
                - name: fedora-35
                  label: fedora-35
    promote:
      jobs:
        - zuul-promote-docs
