- name: Run the download-artifacts role
  hosts: all
  roles:
    - ensure-output-dirs

  tasks:
    # NOTE(ianw) : This has probably expired and thus broken this
    # test.  You need to choose a new artifact to download to test
    # this as part of updating the download-artifact role

    - name: Download centos 7 x86 artifact on host
      include_role:
        name: download-artifact
      vars:
        download_artifact_query: "change=733420&patchset=1&pipeline=gate&job_name=openafs-rpm-package-build-centos-7-x86"
        download_artifact_api: "https://zuul.opendev.org/api/tenant/openstack"
        download_artifact_type: rpm
        download_artifact_pipeline: gate
        download_artifact_job: openafs-rpm-package-build-centos-7-x86
        download_artifact_directory: '/tmp/'
        download_artifact_recurse: yes

    - name: Download centos 7 x86 artifact on executor
      include_role:
        name: download-artifact
        apply:
          delegate_to: localhost
      vars:
        download_artifact_query: "change=733420&patchset=1&pipeline=gate&job_name=openafs-rpm-package-build-centos-7-x86"
        download_artifact_api: "https://zuul.opendev.org/api/tenant/openstack"
        download_artifact_type: rpm
        download_artifact_pipeline: gate
        download_artifact_job: openafs-rpm-package-build-centos-7-x86
        download_artifact_directory: '{{ zuul.executor.work_root }}/test-artifacts/'
        download_artifact_recurse: yes
