- hosts: all
  tasks:
    - name: Run bindep
      include_role:
        name: bindep
    - name: Run tox with constraints
      include_role:
        name: tox
      vars:
        tox_envlist: docs
        tox_constraints_file: '{{ zuul.project.src_dir }}/zuul-tests.d/test-constraints.txt'
        tox_environment:
          ANSIBLE_ROLES_PATH: "{{ ansible_user_dir }}/{{ zuul.project.src_dir }}/roles"
          ANSIBLE_LIBRARY: "{{ ansible_user_dir }}/{{ zuul.project.src_dir }}/tests/fake-ansible"
