- name: Add all repositories
  include_role:
    name: ensure-package-repositories
  vars:
    repositories_list:
      - repo: ppa:projectatomic/ppa

- name: Install podman
  package:
    name:
      - podman
      - uidmap
      - slirp4netns
    state: present
  become: yes
