- name: Create temp directory
  tempfile:
    state: directory
  register: bazel_installer_tempdir

- name: Get installer checksum
  uri:
    url: "{{ bazel_release_url }}/{{ bazel_version }}/bazel-{{ bazel_version }}-installer-linux-x86_64.sh.sha256"
    return_content: true
  register: bazel_installer_checksum

- debug:
    msg: "Checksum is {{ bazel_installer_checksum.content.split(' ')[0] }}"

- name: Download bazel installer
  get_url:
    url: "{{ bazel_release_url }}/{{ bazel_version }}/bazel-{{ bazel_version }}-installer-linux-x86_64.sh"
    dest: "{{ bazel_installer_tempdir.path }}/bazel-{{ bazel_version }}-installer-linux-x86_64.sh"
    mode: 0755
    checksum: "sha256:{{ bazel_installer_checksum.content.split(' ')[0] }}"

- debug:
    msg: "Distribution is {{ ansible_distribution }}"
- debug:
    msg: "OS family is {{ ansible_os_family }}"

- name: Install bazel and platform-specific dependencies
  include_tasks: "{{ zj_distro_os }}"
  with_first_found:
    - "{{ ansible_distribution }}.yaml"
    - "{{ ansible_os_family }}.yaml"
    - "default.yaml"
  loop_control:
    loop_var: zj_distro_os
