---
- name: Create result dir
  file:
    path: "{{ ansible_env.HOME }}/test-results/{{ item.url.rstrip('/')|basename }}"
    state: directory

- name: Fetch artifact
  get_url:
    url: "{{ item.url }}/composite.xml"
    dest: "{{ ansible_env.HOME }}/test-results/{{ item.url.rstrip('/')|basename }}/composite.xml"
