# Install sibling with tox so we can replace them later
- name: Run tox without tests
  command: >-
    {{ tox_executable }}
    --notest
    -e{{ _tox_envlist }}
  args:
    chdir: "{{ zuul_work_dir }}"
  environment: "{{ tox_environment|combine(tox_constraints_env|default({})) }}"

# This is needed since python < 3.2 can't parse ini files from strings
- name: Create a tempfile to save tox showconfig
  tempfile:
  register: _tox_show_config_tempfile

# py27, py35..py38 etc are generated on the fly if not
# explicitly added to tox.ini, so force tox to generate
# the config for the testenvs we're using.
- name: Get tox envlist config
  shell: "{{ tox_executable }} --showconfig -e {{ _tox_envlist }} > {{ _tox_show_config_tempfile.path }}"
  args:
    chdir: "{{ zuul_work_dir }}"

- name: Install any sibling python packages
  tox_install_sibling_packages:
    tox_envlist: "{{ _tox_envlist }}"
    tox_show_config: "{{ _tox_show_config_tempfile.path }}"
    tox_constraints_file: "{{ tox_constraints_file | default(omit) }}"
    project_dir: "{{ zuul_work_dir }}"
    projects: "{{ zuul.projects.values() | selectattr('required') | list }}"

- name: Remove tempfile
  file:
    state: absent
    path: "{{ _tox_show_config_tempfile.path }}"
