---

- name: Ensure "docker" group exists
  group:
    name: "{{ docker_group }}"
    state: present

- name: Add user to docker group
  user:
    name: "{{ ansible_user }}"
    groups:
      - "{{ docker_group }}"
    append: yes

- name: Update docker daemon configuration
  when: docker_userland_proxy is defined
  block:
    - name: Add proxy config
      include_role:
        name: update-json-file
      vars:
        update_json_file_name: /etc/docker/daemon.json
        update_json_file_combine:
          userland-proxy: "{{ docker_userland_proxy }}"
        update_json_file_become: true

- name: Reset ssh connection to pick up docker group
  meta: reset_connection
