---

- name: Install pre-reqs
  package:
    name: "{{ _docker_upstream_distro_required_packages }}"
    state: present

- name: Add docker GPG key
  apt_key:
    data: "{{ docker_gpg_key }}"

# TODO(mordred) We should add a proxy cache mirror for this
- name: Add docker apt repo
  template:
    dest: /etc/apt/sources.list.d/docker.list
    group: root
    mode: 0644
    owner: root
    src: sources.list.j2

- include_tasks: upstream-package-installation.yaml
