- name: Create .pypirc configuration file tempfile
  tempfile:
    state: file
  register: _pypirc_tmp

- name: Create .pypirc configuration file
  template:
    dest: "{{ _pypirc_tmp.path }}"
    mode: 0400
    src: .pypirc.j2

- name: Find wheels to upload
  find:
    paths: "{{ pypi_path }}"
    patterns: "*.whl"
    excludes: "*-linux_x86_64.whl"
  register: found_wheels

- name: Report no wheels to be uploaded
  debug:
    msg: "Found no wheels to upload: {{ found_wheels.msg }}"
  when: found_wheels.files == []

- name: Register packages on the PyPI server (via wheels)
  command: "{{ pypi_twine_executable }} register --config-file {{ _pypirc_tmp.path }} --repository {{ pypi_repository }} {{ zj_wheel.path }}"
  with_items: "{{ found_wheels.files }}"
  loop_control:
    loop_var: zj_wheel
  when: pypi_register_first

- name: Upload wheel with twine before tarballs
  command: "{{ pypi_twine_executable }} upload --config-file {{ _pypirc_tmp.path }} -r {{ pypi_repository }} {{ zj_wheel.path }}"
  with_items: "{{ found_wheels.files }}"
  loop_control:
    loop_var: zj_wheel

- name: Find tarballs to upload
  find:
    paths: "{{ pypi_path }}"
    patterns: "*.tar.gz"
  register: found_tarballs

- name: Report no tarballs to be uploaded
  debug:
    msg: "Found no tarballs to upload: {{ found_tarballs.msg }}"
  when: found_tarballs.files == []

- name: Register packages on the PyPI server (via tarballs)
  command: "{{ pypi_twine_executable }} register --config-file {{ _pypirc_tmp.path }} --repository {{ pypi_repository }} {{ zj_tarball.path }}"
  with_items: "{{ found_tarballs.files }}"
  loop_control:
    loop_var: zj_tarball
  when:
    - pypi_register_first
    - found_wheels.files == []

- name: Upload tarballs with twine
  command: "{{ pypi_twine_executable }} upload --config-file {{ _pypirc_tmp.path }} -r {{ pypi_repository }} {{ zj_tarball.path }}"
  with_items: "{{ found_tarballs.files }}"
  loop_control:
    loop_var: zj_tarball

- name: Delete .pypirc configuration file
  file:
    path: "{{ _pypirc_tmp.path }}"
    state: absent
