- name: Write buildkit.toml file
  template:
    dest: /tmp/buildkitd.toml
    src: buildkitd.toml.j2

- name: Run binfmt container
  command: docker run --rm --privileged docker/binfmt:a7996909642ee92942dcd6cff44b9b95f08dad64
  environment:
    DOCKER_CLI_EXPERIMENTAL: enabled

- name: Create builder
  command: docker buildx create --name mybuilder --driver-opt network=host --config /tmp/buildkitd.toml
  environment:
    DOCKER_CLI_EXPERIMENTAL: enabled

- name: Use builder
  command: docker buildx use mybuilder
  environment:
    DOCKER_CLI_EXPERIMENTAL: enabled

- name: Bootstrap builder
  command: docker buildx inspect --bootstrap
  environment:
    DOCKER_CLI_EXPERIMENTAL: enabled

- name: Copy buildset registry TLS cert into worker container
  command: "docker cp {{ ca_dir }}/buildset-registry.crt buildx_buildkit_mybuilder0:/usr/local/share/ca-certificates"

- name: Update CA certs in worker container
  command: docker exec buildx_buildkit_mybuilder0 update-ca-certificates

- name: Copy /etc/hosts for editing
  command: docker cp buildx_buildkit_mybuilder0:/etc/hosts /tmp/mybuilder-hosts

# Docker buildx has its own /etc/hosts in the builder image.
- name: Configure /etc/hosts for buildset_registry to workaround docker not understanding ipv6 addresses
  become: yes
  lineinfile:
    path: /tmp/mybuilder-hosts
    state: present
    regex: "^{{ buildset_registry.host }}\tzuul-jobs.buildset-registry$"
    line: "{{ buildset_registry.host }}\tzuul-jobs.buildset-registry"
    insertafter: EOF
  when: buildset_registry is defined and buildset_registry.host | ipaddr

- name: Unmount the /etc/hosts mount
  command: docker exec buildx_buildkit_mybuilder0 umount /etc/hosts

# NOTE(mordred) This is done in two steps. Even though we've unmounted /etc/hosts
# in the previous step, when we try to copy the file back directly, we get:
#   unlinkat /etc/hosts: device or resource busy
- name: Copy modified hosts file back in
  command: docker cp /tmp/mybuilder-hosts buildx_buildkit_mybuilder0:/etc/new-hosts

- name: Copy modified hosts file into place
  command: docker exec buildx_buildkit_mybuilder0 cp /etc/new-hosts /etc/hosts
