- name: Install JDK
  package:
    name: java-latest-openjdk
    state: present
  become: true

- name: Create /tmp/zookeeper
  file:
    path: /tmp/zookeeper
    state: directory
  become: true

- name: Get and extract Zookeeper
  unarchive:
    src: https://archive.apache.org/dist/zookeeper/zookeeper-{{ _zookeeper_install_version }}/apache-zookeeper-{{ _zookeeper_install_version }}-bin.tar.gz
    dest: /tmp/zookeeper
    remote_src: yes
  become: true

- name: Link install to a known location
  file:
    src: /tmp/zookeeper/apache-zookeeper-{{ _zookeeper_install_version }}-bin
    dest: /opt/zookeeper
    state: link
  become: true

- name: Setup Zookeeper config file
  copy:
    src: /opt/zookeeper/conf/zoo_sample.cfg
    dest: /opt/zookeeper/conf/zoo.cfg
    remote_src: true
  become: true

- name: Ensure Zookeeper not running
  command: pkill -f zookeeper
  ignore_errors: true
  become: true

- name: Start Zookeeper
  command: /opt/zookeeper/bin/zkServer.sh start
  become: true
