# See notes in main.yaml about the virtualenv requirements

- name: Install Python 3 pip
  package:
    name:
      - python3-pip
      - python3-setuptools
      - python3-venv
      - python3-virtualenv
  become: yes

- name: Install Python 2 pip
  package:
    name:
      - python-setuptools
      - python-pip
      - python-virtualenv
  become: yes
  when: (ensure_pip_from_packages_with_python2) or
        (ansible_python.version.major == 2)
